### ISSUE TITLE
No module named 'metric.cityscapes_mIoU'

### ISSUE THREAD

**Issue by deepseek** [mit-han-lab/gan-compression#34]
Hi there, @junyanz @lmxyy 
when trying to train a "once-for-all" network, i get error:
```
(gan) home@home-lnx:~/programs/level 2/gan-compression$ bash scripts/cycle_gan/horse2zebra_lite/train_supernet.sh
Traceback (most recent call last):
  File "train_supernet.py", line 4, in <module>
    trainer = Trainer('supernet')
  File "/home/home/programs/level 2/gan-compression/trainer.py", line 38, in __init__
    opt = Options().parse()
  File "/home/home/programs/level 2/gan-compression/options/base_options.py", line 134, in parse
    opt = self.gather_options()
  File "/home/home/programs/level 2/gan-compression/options/supernet_options.py", line 76, in gather_options
    supernet_option_setter = supernets.get_option_setter(supernet_name)
  File "/home/home/programs/level 2/gan-compression/supernets/__init__.py", line 22, in get_option_setter
    supernet_class = find_supernet_using_name(supernet_name)
  File "/home/home/programs/level 2/gan-compression/supernets/__init__.py", line 6, in find_supernet_using_name
    modellib = importlib.import_module(supernet_filename)
  File "/home/home/anaconda3/envs/gan/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/home/programs/level 2/gan-compression/supernets/resnet_supernet.py", line 13, in <module>
    from distillers.base_resnet_distiller import BaseResnetDistiller
  File "/home/home/programs/level 2/gan-compression/distillers/base_resnet_distiller.py", line 11, in <module>
    from metric.cityscapes_mIoU import DRNSeg
ModuleNotFoundError: No module named 'metric.cityscapes_mIoU'
```

**Comment by lmxyy** [comment]
Thanks for pointing out. They are some mistakes from my merging. I've fixed them. 
Feel free to open issues if you have any other questions!
