### ISSUE TITLE
NotImplementedError: Unknown module [<class 'torch.nn.modules.instancenorm.InstanceNorm2d'>]!

### ISSUE THREAD

**Issue by edvardHua** [mit-han-lab/gan-compression#37]
Following the tutorial, i train the mobile style CycleGAN. (Without changing parameters except the dataset)

But when i runing train_supernet.sh, it end up with the following error.

```bash
Traceback (most recent call last):
  File "train_supernet.py", line 4, in <module>
    trainer = Trainer('supernet')
  File "/data1/edvardzeng/myspace/gan-compression/trainer.py", line 52, in __init__
    model.setup(opt)  # regular setup: load and print networks; create schedulers
  File "/data1/edvardzeng/myspace/gan-compression/distillers/base_resnet_distiller.py", line 153, in setup
    self.load_networks(verbose)
  File "/data1/edvardzeng/myspace/gan-compression/supernets/resnet_supernet.py", line 182, in load_networks
    self.opt.student_ngf, self.opt.student_ngf)
  File "/data1/edvardzeng/myspace/gan-compression/utils/weight_transfer.py", line 167, in load_pretrained_weight
    index = transfer(m1, m2, index)
  File "/data1/edvardzeng/myspace/gan-compression/utils/weight_transfer.py", line 139, in transfer
    return transfer_MobileResnetBlock(m1, m2, input_index, output_index)
  File "/data1/edvardzeng/myspace/gan-compression/utils/weight_transfer.py", line 84, in transfer_MobileResnetBlock
    idxs = transfer(m1.conv_block[1], m2.conv_block[1], input_index=input_index)
  File "/data1/edvardzeng/myspace/gan-compression/utils/weight_transfer.py", line 145, in transfer
    raise NotImplementedError('Unknown module [%s]!' % type(m1))
NotImplementedError: Unknown module [<class 'torch.nn.modules.instancenorm.InstanceNorm2d'>]!
```

**Comment by lmxyy** [comment]
Could you please provide your commands so I could take a deeper look?

**Comment by edvardHua** [comment]
Thanks for you reply. 

Problem solved, the reason is because i change the network architecture.

😄
