### ISSUE TITLE
(param 'initial_lr' is not specified) when resuming training

### ISSUE THREAD

**Issue by seekingdeep** [mit-han-lab/gan-compression#72]
Hi there,
i am trying to resume training of a model, from epoch 5 iteration 60000
But i get error:
```
(gan) home@home-lnx:~/programs/gan-compression$ python train.py --dataroot database/edges2shoes-r --model pix2pix --netG resnet_9blocks --log_dir logs/pix2pix/edges2shoes-r/train2 --real_stat_path real_stat/edges2shoes-r_B.npz --batch_size 8 --restore_G_path pretrained/pix2pix/edges2shoes-r/full/iter60000_net_G.pth --epoch_base 10 --iter_base 60000 --save_latest_freq 10000 --lr 0.0002
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 8                             	[default: 1]
                    beta1: 0.5                           
calibration_load_in_memory: False                         
    calibration_meta_path: None                          
          cityscapes_path: database/cityscapes-origin    
               config_set: None                          
               config_str: None                          
                crop_size: 256                           
                 dataroot: database/edges2shoes-r        	[default: None]
             dataset_mode: aligned                       
           deeplabv2_path: deeplabv2_resnet101_msc-cocostuff164k-100000.pth
                direction: AtoB                          
          display_winsize: 256                           
                 drn_path: drn-d-105_ms_cityscapes.pth   
             dropout_rate: 0                             
               epoch_base: 10                            	[default: 1]
          eval_batch_size: 1                             
                    gamma: 0.5                           
                 gan_mode: hinge                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: True                          	[default: None]
                iter_base: 60000                         	[default: 0]
               lambda_gan: 1                             
             lambda_recon: 100                           
           load_in_memory: False                         
                load_size: 256                           
                  log_dir: logs/pix2pix/edges2shoes-r/train2	[default: logs]
                       lr: 0.0002                        
           lr_decay_steps: 100000                        
                lr_policy: linear                        
         max_dataset_size: -1                            
                meta_path: None                          
                    model: pix2pix                       
               n_layers_D: 3                             
                      ndf: 128                           
                  nepochs: 10000                         
            nepochs_decay: 15                            
                     netD: n_layers                      
                     netG: resnet_9blocks                	[default: mobile_resnet_9blocks]
                      ngf: 64                            
                   niters: 1000000000                    
                   no_fid: False                         
                  no_flip: False                         
                  no_mIoU: False                         
                     norm: instance                      
              num_threads: 4                             
                output_nc: 3                             
                    phase: train                         
                pool_size: 50                            
               preprocess: resize_and_crop               
               print_freq: 100                           
           real_stat_path: real_stat/edges2shoes-r_B.npz 	[default: None]
          recon_loss_type: l1                            
           restore_D_path: None                          
           restore_G_path: pretrained/pix2pix/edges2shoes-r/full/iter60000_net_G.pth	[default: None]
           restore_O_path: None                          
          save_epoch_freq: 5                             
         save_latest_freq: 10000                         	[default: 20000]
        scheduler_counter: epoch                         
                     seed: 233                           
           serial_batches: False                         
               table_path: datasets/val_table.txt        
          tensorboard_dir: None                          
----------------- End -------------------
train.py --dataroot database/edges2shoes-r --model pix2pix --netG resnet_9blocks --log_dir logs/pix2pix/edges2shoes-r/train2 --real_stat_path real_stat/edges2shoes-r_B.npz --batch_size 8 --restore_G_path pretrained/pix2pix/edges2shoes-r/full/iter60000_net_G.pth --epoch_base 10 --iter_base 60000 --save_latest_freq 10000 --lr 0.0002
dataset [AlignedDataset] was created
The number of training images = 65675
initialize network with normal
initialize network with normal
dataset [AlignedDataset] was created
model [Pix2PixModel] was created
Load network at pretrained/pix2pix/edges2shoes-r/full/iter60000_net_G.pth
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    trainer = Trainer('train')
  File "/home/home/programs/gan-compression/trainer.py", line 53, in __init__
    model.setup(opt)  # regular setup: load and print networks; create schedulers
  File "/home/home/programs/gan-compression/models/base_model.py", line 91, in setup
    self.schedulers = [networks.get_scheduler(optimizer, opt) for optimizer in self.optimizers]
  File "/home/home/programs/gan-compression/models/base_model.py", line 91, in <listcomp>
    self.schedulers = [networks.get_scheduler(optimizer, opt) for optimizer in self.optimizers]
  File "/home/home/programs/gan-compression/models/networks.py", line 72, in get_scheduler
    scheduler = lr_scheduler.LambdaLR(optimizer, lr_lambda=lambda_rule, last_epoch=last_epoch)
  File "/home/home/anaconda3/envs/gan/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 189, in __init__
    super(LambdaLR, self).__init__(optimizer, last_epoch)
  File "/home/home/anaconda3/envs/gan/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 40, in __init__
    raise KeyError("param 'initial_lr' is not specified "
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"
```

**Comment by seekingdeep** [comment]
@lmxyy

**Comment by seekingdeep** [comment]
the problem is solved, i've added the following:
```
--restore_G_path pretrained/pix2pix/edges2shoes-r/full/iter60000_net_G.pth --restore_D_path pretrained/pix2pix/edges2shoes-r/full/iter60000_net_D.pth --restore_O_path pretrained/pix2pix/edges2shoes-r/full/iter60000_optim
```
